//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type AccountsContacts struct {
	ID         uint32 `sql:"primary_key"`
	AccountID  uint32
	Name       string
	Position   string
	Phone      string
	Email      string
	IsRequired uint8
	UserAdd    *uint32
	UserEdit   *uint32
	DateAdd    time.Time
	DateEdit   *time.Time
}
