//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Accounts struct {
	ID                 uint32 `sql:"primary_key"`
	SubserviceID       uint32
	Name               string
	Img                *string
	Description        *string
	Status             uint8 // 1 - Активный, 2 - Неактивный
	IsActiveContractor uint8 // 1- Активный, 0 - Неактивный
	DateAdd            time.Time
	DateEdit           *time.Time
	AllowIps           *string
}
