//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type AccountsRatings struct {
	ID        uint32 `sql:"primary_key"`
	AccountID uint32
	Value     uint8
	Cause     string
	DateAdd   time.Time
	UserAdd   *uint32
}
