//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Categories struct {
	ID              uint32 `sql:"primary_key"`
	SubserviceID    uint32
	ParentID        *uint32
	Name            string
	Description     *string
	Level           uint32
	Position        uint32
	Code            string
	IsViewPreOffers uint8
	IsViewOffers    uint8
	UserAdd         *uint32
	UserEdit        *uint32
	DateAdd         time.Time
	DateEdit        *time.Time
}
