//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type CategoriesUsersRights struct {
	ID            uint32 `sql:"primary_key"`
	CategoryID    uint32
	UserID        *uint32
	AccountID     *uint32
	SuspendUntil  *time.Time
	Status        uint8 // 0 - Новая,1 - Принята, 2 - Отклонена, 3 - Обновлена
	ExternalCause *string
	InternalCause *string
	UserAdd       *uint32
	UserEdit      *uint32
	DateAdd       time.Time
	DateEdit      *time.Time
}
