//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type CountriesRegionsLocalities struct {
	ID       uint32 `sql:"primary_key"`
	RegionID uint32
	Name     string
	Type     uint8 // 1 - Город, 2 - Село, 3 - ПГТ
	UserAdd  *uint32
	UserEdit *uint32
	DateAdd  time.Time
	DateEdit *time.Time
}
