//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type FaqType string

const (
	FaqType_Organizer FaqType = "organizer"
	FaqType_Member    FaqType = "member"
)

func (e *FaqType) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "organizer":
		*e = FaqType_Organizer
	case "member":
		*e = FaqType_Member
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for FaqType enum")
	}

	return nil
}

func (e FaqType) String() string {
	return string(e)
}
