//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type Geoip struct {
	ID          uint32 `sql:"primary_key"`
	RangeBegin  *uint32
	RangeEnd    *uint32
	CountryCode string
	CountryName *string
}
