//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type GroupsRecipients struct {
	ID           uint32 `sql:"primary_key"`
	SubserviceID uint32
	CategoryID   *uint32
	Type         bool // 1 - Список имейлов, 2 - Категория
	Name         *string
	UserAdd      *uint32
	UserEdit     *uint32
	DateAdd      time.Time
	DateEdit     *time.Time
}
