//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type InboxMessages struct {
	ID            uint32 `sql:"primary_key"`
	MessageBodyID uint32
	UserSender    uint32
	UserRecipient uint32
	Status        uint32 // 1 - Новое, 2- Прочитано
	DateRead      *time.Time
}
