//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type LogsUsersActions struct {
	ID               uint64 `sql:"primary_key"`
	UserID           *uint32
	ActionType       uint8 // Долго перечислять, будут тут типы те которые в ТЗ
	Essence          uint8
	ActionRelativeID uint32
	Date             time.Time
}
