//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type MailQueueStatus string

const (
	MailQueueStatus_Pending MailQueueStatus = "pending"
	MailQueueStatus_Sent    MailQueueStatus = "sent"
	MailQueueStatus_Error   MailQueueStatus = "error"
)

func (e *MailQueueStatus) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "pending":
		*e = MailQueueStatus_Pending
	case "sent":
		*e = MailQueueStatus_Sent
	case "error":
		*e = MailQueueStatus_Error
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for MailQueueStatus enum")
	}

	return nil
}

func (e MailQueueStatus) String() string {
	return string(e)
}
