//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Mailing struct {
	ID               uint32 `sql:"primary_key"`
	SubserviceID     uint32
	GroupRecipientID uint32
	Name             *int32
	Subject          string
	Content          string
	Status           uint8 // 1 - Новая, 2- В процессе, 3- Отправлена
	UserAdd          *uint32
	UserEdit         *uint32
	DateAdd          time.Time
	DateEdit         *time.Time
	SenderName       string
	SenderEmail      string
	DateSent         *time.Time
}
