//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Products struct {
	ID           uint32 `sql:"primary_key"`
	SubserviceID uint32
	UnitID       uint32
	CategoryID   uint32
	Name         string
	Article      *string
	Description  *string
	Img          *string
	Enabled      uint8 // 1 - On, 0 - Off
	UserAdd      *uint32
	UserEdit     *uint32
	DateAdd      time.Time
	DateEdit     *time.Time
}
