//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Templates struct {
	ID            uint32 `sql:"primary_key"`
	SubserviceID  uint32
	AliasID       string
	Name          string
	Template      *string
	Vars          *string
	EmailSubject  string
	EmailTemplate string
	UserEdit      *uint32
	DateEdit      *time.Time
}
