//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type TendersInvites struct {
	ID              uint32 `sql:"primary_key"`
	TenderID        uint32
	InviteAccountID uint32
	Status          uint8 // 1 - новая, 2 - принята, 3 - отклонена
	UserAdd         uint32
	UserEdit        *uint32
	DateAdd         time.Time
	DateEdit        *time.Time
}
