//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Tenders struct {
	ID                    uint32 `sql:"primary_key"`
	CategoryID            *uint32
	CurrencyID            *uint32
	Mode                  uint8 // 1 - покупка, 2 - продажа
	TypeBid               TendersTypeBid
	IsInvitation          uint8 // 0 - На общих основания, 1 - По приглашению
	IsCollectionPreOffers uint8 // 0 - Обычный, 1 - Сбор предварительных предложений
	IsViewPreOffers       uint8
	IsViewOffers          uint8
	DateStart             *time.Time
	DateEnd               *time.Time
	TradingHoursStart     *time.Time
	TradingHoursEnd       *time.Time
	TradingDateStart      *time.Time
	IsPause               uint8 // 0 - Активен, 1 - На паузе
	IsAutoRenewal         uint8 // 0 - Без автопродления, 1 - С автопродлением
	AutoRenewalValue      *uint32
	Description           *string
	IsTemplate            uint8 // 0 - Не шаблон, 1 - Шаблон
	TemplateName          *string
	IsPublished           uint8 // 0 - Черновик, 1 - Опубликован
	IsCanceled            uint8 // 0 - Не отменен, 1-  отменен
	ExternalCause         *string
	InternalCause         *string
	InviteExternalCause   *string
	InviteInternalCause   *string
	Status                uint8 // 0 - Предстоящий, 1 - Активный, 2 - Завершенный, 3 - торги окончены
	RenewalExternalCause  string
	RenewalInternalCause  string
	UserAdd               uint32
	UserEdit              *uint32
	DateAdd               time.Time
	DateEdit              *time.Time
}
