//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type TendersLotsFormulasParameters struct {
	ID                 uint32 `sql:"primary_key"`
	TenderLotID        uint32
	FormulaParameterID uint32
	MinValue           *float64
	MaxValue           *float64
}
