//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type TendersRequestsAndInvites struct {
	ID          uint32
	TenderID    uint32
	AccountName string
	DateAdd     time.Time
	Comment     *string
	Status      uint8
	AccountID   uint32
	Type        int64
}
