//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type TendersLotsLotsOptions struct {
	ID               uint32 `sql:"primary_key"`
	TenderLotID      uint32
	LotOptionID      uint32
	LotOptionValueID uint32
	Enabled          uint8 // 0 - Off, 1 -On
}
