//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type TendersLotsOffers struct {
	ID                  uint32 `sql:"primary_key"`
	TenderLotID         uint32
	Offer               float64
	Description         *string
	DateAdd             time.Time
	DateWin             *time.Time
	UserAdd             uint32
	IsCanceled          uint8 // 0 - Не отменена, 1 - Отменена
	IsWinner            uint8 // 0 - Не победитель, 1 - Победитель
	NotBid              int8
	InternalCause       *string
	ExternalCause       *string
	WinnerInternalCause *string
	WinnerExternalCause *string
}
