//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type TendersLotsProducts struct {
	ID          uint32 `sql:"primary_key"`
	TenderLotID uint32
	ProductID   uint32
	Count       float64
	Price       float64
}
