//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Units struct {
	ID           uint32 `sql:"primary_key"`
	SubserviceID uint32
	Name         string
	Value        string
	UserAdd      *uint32
	UserEdit     *uint32
	DateAdd      time.Time
	DateEdit     *time.Time
}
