//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/mysql"

var MailQueueStatus = &struct {
	Pending mysql.StringExpression
	Sent    mysql.StringExpression
	Error   mysql.StringExpression
}{
	Pending: mysql.NewEnumValue("pending"),
	Sent:    mysql.NewEnumValue("sent"),
	Error:   mysql.NewEnumValue("error"),
}
