//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/mysql"

var TendersTypeBid = &struct {
	Tender           mysql.StringExpression
	CollectionOffers mysql.StringExpression
}{
	Tender:           mysql.NewEnumValue("tender"),
	CollectionOffers: mysql.NewEnumValue("collection_offers"),
}
