//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var LotsOptions = newLotsOptionsTable("newtendex", "lots_options", "")

type lotsOptionsTable struct {
	mysql.Table

	// Columns
	ID           mysql.ColumnInteger
	SubserviceID mysql.ColumnInteger
	Name         mysql.ColumnString
	UserAdd      mysql.ColumnInteger
	UserEdit     mysql.ColumnInteger
	DateAdd      mysql.ColumnTimestamp
	DateEdit     mysql.ColumnTimestamp

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
}

type LotsOptionsTable struct {
	lotsOptionsTable

	NEW lotsOptionsTable
}

// AS creates new LotsOptionsTable with assigned alias
func (a LotsOptionsTable) AS(alias string) *LotsOptionsTable {
	return newLotsOptionsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new LotsOptionsTable with assigned schema name
func (a LotsOptionsTable) FromSchema(schemaName string) *LotsOptionsTable {
	return newLotsOptionsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new LotsOptionsTable with assigned table prefix
func (a LotsOptionsTable) WithPrefix(prefix string) *LotsOptionsTable {
	return newLotsOptionsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new LotsOptionsTable with assigned table suffix
func (a LotsOptionsTable) WithSuffix(suffix string) *LotsOptionsTable {
	return newLotsOptionsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newLotsOptionsTable(schemaName, tableName, alias string) *LotsOptionsTable {
	return &LotsOptionsTable{
		lotsOptionsTable: newLotsOptionsTableImpl(schemaName, tableName, alias),
		NEW:              newLotsOptionsTableImpl("", "new", ""),
	}
}

func newLotsOptionsTableImpl(schemaName, tableName, alias string) lotsOptionsTable {
	var (
		IDColumn           = mysql.IntegerColumn("id")
		SubserviceIDColumn = mysql.IntegerColumn("subservice_id")
		NameColumn         = mysql.StringColumn("name")
		UserAddColumn      = mysql.IntegerColumn("user_add")
		UserEditColumn     = mysql.IntegerColumn("user_edit")
		DateAddColumn      = mysql.TimestampColumn("date_add")
		DateEditColumn     = mysql.TimestampColumn("date_edit")
		allColumns         = mysql.ColumnList{IDColumn, SubserviceIDColumn, NameColumn, UserAddColumn, UserEditColumn, DateAddColumn, DateEditColumn}
		mutableColumns     = mysql.ColumnList{SubserviceIDColumn, NameColumn, UserAddColumn, UserEditColumn, DateAddColumn, DateEditColumn}
	)

	return lotsOptionsTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:           IDColumn,
		SubserviceID: SubserviceIDColumn,
		Name:         NameColumn,
		UserAdd:      UserAddColumn,
		UserEdit:     UserEditColumn,
		DateAdd:      DateAddColumn,
		DateEdit:     DateEditColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
