//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var Products = newProductsTable("newtendex", "products", "")

type productsTable struct {
	mysql.Table

	// Columns
	ID           mysql.ColumnInteger
	SubserviceID mysql.ColumnInteger
	UnitID       mysql.ColumnInteger
	CategoryID   mysql.ColumnInteger
	Name         mysql.ColumnString
	Article      mysql.ColumnString
	Description  mysql.ColumnString
	Img          mysql.ColumnString
	Enabled      mysql.ColumnInteger // 1 - On, 0 - Off
	UserAdd      mysql.ColumnInteger
	UserEdit     mysql.ColumnInteger
	DateAdd      mysql.ColumnTimestamp
	DateEdit     mysql.ColumnTimestamp

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
}

type ProductsTable struct {
	productsTable

	NEW productsTable
}

// AS creates new ProductsTable with assigned alias
func (a ProductsTable) AS(alias string) *ProductsTable {
	return newProductsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new ProductsTable with assigned schema name
func (a ProductsTable) FromSchema(schemaName string) *ProductsTable {
	return newProductsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new ProductsTable with assigned table prefix
func (a ProductsTable) WithPrefix(prefix string) *ProductsTable {
	return newProductsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new ProductsTable with assigned table suffix
func (a ProductsTable) WithSuffix(suffix string) *ProductsTable {
	return newProductsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newProductsTable(schemaName, tableName, alias string) *ProductsTable {
	return &ProductsTable{
		productsTable: newProductsTableImpl(schemaName, tableName, alias),
		NEW:           newProductsTableImpl("", "new", ""),
	}
}

func newProductsTableImpl(schemaName, tableName, alias string) productsTable {
	var (
		IDColumn           = mysql.IntegerColumn("id")
		SubserviceIDColumn = mysql.IntegerColumn("subservice_id")
		UnitIDColumn       = mysql.IntegerColumn("unit_id")
		CategoryIDColumn   = mysql.IntegerColumn("category_id")
		NameColumn         = mysql.StringColumn("name")
		ArticleColumn      = mysql.StringColumn("article")
		DescriptionColumn  = mysql.StringColumn("description")
		ImgColumn          = mysql.StringColumn("img")
		EnabledColumn      = mysql.IntegerColumn("enabled")
		UserAddColumn      = mysql.IntegerColumn("user_add")
		UserEditColumn     = mysql.IntegerColumn("user_edit")
		DateAddColumn      = mysql.TimestampColumn("date_add")
		DateEditColumn     = mysql.TimestampColumn("date_edit")
		allColumns         = mysql.ColumnList{IDColumn, SubserviceIDColumn, UnitIDColumn, CategoryIDColumn, NameColumn, ArticleColumn, DescriptionColumn, ImgColumn, EnabledColumn, UserAddColumn, UserEditColumn, DateAddColumn, DateEditColumn}
		mutableColumns     = mysql.ColumnList{SubserviceIDColumn, UnitIDColumn, CategoryIDColumn, NameColumn, ArticleColumn, DescriptionColumn, ImgColumn, EnabledColumn, UserAddColumn, UserEditColumn, DateAddColumn, DateEditColumn}
	)

	return productsTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:           IDColumn,
		SubserviceID: SubserviceIDColumn,
		UnitID:       UnitIDColumn,
		CategoryID:   CategoryIDColumn,
		Name:         NameColumn,
		Article:      ArticleColumn,
		Description:  DescriptionColumn,
		Img:          ImgColumn,
		Enabled:      EnabledColumn,
		UserAdd:      UserAddColumn,
		UserEdit:     UserEditColumn,
		DateAdd:      DateAddColumn,
		DateEdit:     DateEditColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
