//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var Tenders = newTendersTable("newtendex", "tenders", "")

type tendersTable struct {
	mysql.Table

	// Columns
	ID                    mysql.ColumnInteger
	CategoryID            mysql.ColumnInteger
	CurrencyID            mysql.ColumnInteger
	Mode                  mysql.ColumnInteger // 1 - покупка, 2 - продажа
	TypeBid               mysql.ColumnString
	IsInvitation          mysql.ColumnInteger // 0 - На общих основания, 1 - По приглашению
	IsCollectionPreOffers mysql.ColumnInteger // 0 - Обычный, 1 - Сбор предварительных предложений
	IsViewPreOffers       mysql.ColumnInteger
	IsViewOffers          mysql.ColumnInteger
	DateStart             mysql.ColumnTimestamp
	DateEnd               mysql.ColumnTimestamp
	TradingHoursStart     mysql.ColumnTime
	TradingHoursEnd       mysql.ColumnTime
	TradingDateStart      mysql.ColumnTimestamp
	IsPause               mysql.ColumnInteger // 0 - Активен, 1 - На паузе
	IsAutoRenewal         mysql.ColumnInteger // 0 - Без автопродления, 1 - С автопродлением
	AutoRenewalValue      mysql.ColumnInteger
	Description           mysql.ColumnString
	IsTemplate            mysql.ColumnInteger // 0 - Не шаблон, 1 - Шаблон
	TemplateName          mysql.ColumnString
	IsPublished           mysql.ColumnInteger // 0 - Черновик, 1 - Опубликован
	IsCanceled            mysql.ColumnInteger // 0 - Не отменен, 1-  отменен
	ExternalCause         mysql.ColumnString
	InternalCause         mysql.ColumnString
	InviteExternalCause   mysql.ColumnString
	InviteInternalCause   mysql.ColumnString
	Status                mysql.ColumnInteger // 0 - Предстоящий, 1 - Активный, 2 - Завершенный, 3 - торги окончены
	RenewalExternalCause  mysql.ColumnString
	RenewalInternalCause  mysql.ColumnString
	UserAdd               mysql.ColumnInteger
	UserEdit              mysql.ColumnInteger
	DateAdd               mysql.ColumnTimestamp
	DateEdit              mysql.ColumnTimestamp

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
}

type TendersTable struct {
	tendersTable

	NEW tendersTable
}

// AS creates new TendersTable with assigned alias
func (a TendersTable) AS(alias string) *TendersTable {
	return newTendersTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new TendersTable with assigned schema name
func (a TendersTable) FromSchema(schemaName string) *TendersTable {
	return newTendersTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new TendersTable with assigned table prefix
func (a TendersTable) WithPrefix(prefix string) *TendersTable {
	return newTendersTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new TendersTable with assigned table suffix
func (a TendersTable) WithSuffix(suffix string) *TendersTable {
	return newTendersTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newTendersTable(schemaName, tableName, alias string) *TendersTable {
	return &TendersTable{
		tendersTable: newTendersTableImpl(schemaName, tableName, alias),
		NEW:          newTendersTableImpl("", "new", ""),
	}
}

func newTendersTableImpl(schemaName, tableName, alias string) tendersTable {
	var (
		IDColumn                    = mysql.IntegerColumn("id")
		CategoryIDColumn            = mysql.IntegerColumn("category_id")
		CurrencyIDColumn            = mysql.IntegerColumn("currency_id")
		ModeColumn                  = mysql.IntegerColumn("mode")
		TypeBidColumn               = mysql.StringColumn("type_bid")
		IsInvitationColumn          = mysql.IntegerColumn("is_invitation")
		IsCollectionPreOffersColumn = mysql.IntegerColumn("is_collection_pre_offers")
		IsViewPreOffersColumn       = mysql.IntegerColumn("is_view_pre_offers")
		IsViewOffersColumn          = mysql.IntegerColumn("is_view_offers")
		DateStartColumn             = mysql.TimestampColumn("date_start")
		DateEndColumn               = mysql.TimestampColumn("date_end")
		TradingHoursStartColumn     = mysql.TimeColumn("trading_hours_start")
		TradingHoursEndColumn       = mysql.TimeColumn("trading_hours_end")
		TradingDateStartColumn      = mysql.TimestampColumn("trading_date_start")
		IsPauseColumn               = mysql.IntegerColumn("is_pause")
		IsAutoRenewalColumn         = mysql.IntegerColumn("is_auto_renewal")
		AutoRenewalValueColumn      = mysql.IntegerColumn("auto_renewal_value")
		DescriptionColumn           = mysql.StringColumn("description")
		IsTemplateColumn            = mysql.IntegerColumn("is_template")
		TemplateNameColumn          = mysql.StringColumn("template_name")
		IsPublishedColumn           = mysql.IntegerColumn("is_published")
		IsCanceledColumn            = mysql.IntegerColumn("is_canceled")
		ExternalCauseColumn         = mysql.StringColumn("external_cause")
		InternalCauseColumn         = mysql.StringColumn("internal_cause")
		InviteExternalCauseColumn   = mysql.StringColumn("invite_external_cause")
		InviteInternalCauseColumn   = mysql.StringColumn("invite_internal_cause")
		StatusColumn                = mysql.IntegerColumn("status")
		RenewalExternalCauseColumn  = mysql.StringColumn("renewal_external_cause")
		RenewalInternalCauseColumn  = mysql.StringColumn("renewal_internal_cause")
		UserAddColumn               = mysql.IntegerColumn("user_add")
		UserEditColumn              = mysql.IntegerColumn("user_edit")
		DateAddColumn               = mysql.TimestampColumn("date_add")
		DateEditColumn              = mysql.TimestampColumn("date_edit")
		allColumns                  = mysql.ColumnList{IDColumn, CategoryIDColumn, CurrencyIDColumn, ModeColumn, TypeBidColumn, IsInvitationColumn, IsCollectionPreOffersColumn, IsViewPreOffersColumn, IsViewOffersColumn, DateStartColumn, DateEndColumn, TradingHoursStartColumn, TradingHoursEndColumn, TradingDateStartColumn, IsPauseColumn, IsAutoRenewalColumn, AutoRenewalValueColumn, DescriptionColumn, IsTemplateColumn, TemplateNameColumn, IsPublishedColumn, IsCanceledColumn, ExternalCauseColumn, InternalCauseColumn, InviteExternalCauseColumn, InviteInternalCauseColumn, StatusColumn, RenewalExternalCauseColumn, RenewalInternalCauseColumn, UserAddColumn, UserEditColumn, DateAddColumn, DateEditColumn}
		mutableColumns              = mysql.ColumnList{CategoryIDColumn, CurrencyIDColumn, ModeColumn, TypeBidColumn, IsInvitationColumn, IsCollectionPreOffersColumn, IsViewPreOffersColumn, IsViewOffersColumn, DateStartColumn, DateEndColumn, TradingHoursStartColumn, TradingHoursEndColumn, TradingDateStartColumn, IsPauseColumn, IsAutoRenewalColumn, AutoRenewalValueColumn, DescriptionColumn, IsTemplateColumn, TemplateNameColumn, IsPublishedColumn, IsCanceledColumn, ExternalCauseColumn, InternalCauseColumn, InviteExternalCauseColumn, InviteInternalCauseColumn, StatusColumn, RenewalExternalCauseColumn, RenewalInternalCauseColumn, UserAddColumn, UserEditColumn, DateAddColumn, DateEditColumn}
	)

	return tendersTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:                    IDColumn,
		CategoryID:            CategoryIDColumn,
		CurrencyID:            CurrencyIDColumn,
		Mode:                  ModeColumn,
		TypeBid:               TypeBidColumn,
		IsInvitation:          IsInvitationColumn,
		IsCollectionPreOffers: IsCollectionPreOffersColumn,
		IsViewPreOffers:       IsViewPreOffersColumn,
		IsViewOffers:          IsViewOffersColumn,
		DateStart:             DateStartColumn,
		DateEnd:               DateEndColumn,
		TradingHoursStart:     TradingHoursStartColumn,
		TradingHoursEnd:       TradingHoursEndColumn,
		TradingDateStart:      TradingDateStartColumn,
		IsPause:               IsPauseColumn,
		IsAutoRenewal:         IsAutoRenewalColumn,
		AutoRenewalValue:      AutoRenewalValueColumn,
		Description:           DescriptionColumn,
		IsTemplate:            IsTemplateColumn,
		TemplateName:          TemplateNameColumn,
		IsPublished:           IsPublishedColumn,
		IsCanceled:            IsCanceledColumn,
		ExternalCause:         ExternalCauseColumn,
		InternalCause:         InternalCauseColumn,
		InviteExternalCause:   InviteExternalCauseColumn,
		InviteInternalCause:   InviteInternalCauseColumn,
		Status:                StatusColumn,
		RenewalExternalCause:  RenewalExternalCauseColumn,
		RenewalInternalCause:  RenewalInternalCauseColumn,
		UserAdd:               UserAddColumn,
		UserEdit:              UserEditColumn,
		DateAdd:               DateAddColumn,
		DateEdit:              DateEditColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
