//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var Units = newUnitsTable("newtendex", "units", "")

type unitsTable struct {
	mysql.Table

	// Columns
	ID           mysql.ColumnInteger
	SubserviceID mysql.ColumnInteger
	Name         mysql.ColumnString
	Value        mysql.ColumnString
	UserAdd      mysql.ColumnInteger
	UserEdit     mysql.ColumnInteger
	DateAdd      mysql.ColumnTimestamp
	DateEdit     mysql.ColumnTimestamp

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
}

type UnitsTable struct {
	unitsTable

	NEW unitsTable
}

// AS creates new UnitsTable with assigned alias
func (a UnitsTable) AS(alias string) *UnitsTable {
	return newUnitsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new UnitsTable with assigned schema name
func (a UnitsTable) FromSchema(schemaName string) *UnitsTable {
	return newUnitsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new UnitsTable with assigned table prefix
func (a UnitsTable) WithPrefix(prefix string) *UnitsTable {
	return newUnitsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new UnitsTable with assigned table suffix
func (a UnitsTable) WithSuffix(suffix string) *UnitsTable {
	return newUnitsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newUnitsTable(schemaName, tableName, alias string) *UnitsTable {
	return &UnitsTable{
		unitsTable: newUnitsTableImpl(schemaName, tableName, alias),
		NEW:        newUnitsTableImpl("", "new", ""),
	}
}

func newUnitsTableImpl(schemaName, tableName, alias string) unitsTable {
	var (
		IDColumn           = mysql.IntegerColumn("id")
		SubserviceIDColumn = mysql.IntegerColumn("subservice_id")
		NameColumn         = mysql.StringColumn("name")
		ValueColumn        = mysql.StringColumn("value")
		UserAddColumn      = mysql.IntegerColumn("user_add")
		UserEditColumn     = mysql.IntegerColumn("user_edit")
		DateAddColumn      = mysql.TimestampColumn("date_add")
		DateEditColumn     = mysql.TimestampColumn("date_edit")
		allColumns         = mysql.ColumnList{IDColumn, SubserviceIDColumn, NameColumn, ValueColumn, UserAddColumn, UserEditColumn, DateAddColumn, DateEditColumn}
		mutableColumns     = mysql.ColumnList{SubserviceIDColumn, NameColumn, ValueColumn, UserAddColumn, UserEditColumn, DateAddColumn, DateEditColumn}
	)

	return unitsTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:           IDColumn,
		SubserviceID: SubserviceIDColumn,
		Name:         NameColumn,
		Value:        ValueColumn,
		UserAdd:      UserAddColumn,
		UserEdit:     UserEditColumn,
		DateAdd:      DateAddColumn,
		DateEdit:     DateEditColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
