//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type AccountDataFields struct {
	ID           uint32 `sql:"primary_key"`
	SubserviceID uint32
	Name         string
	Alias        string
	TypeData     uint8 // 1 - Текст, 2 -Только числа(int), 3 - идентификатор из таблицы accounts_addresses
}
