//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type DocumentsTypes struct {
	ID                uint32 `sql:"primary_key"`
	SubserviceID      uint32
	Name              string
	AllowedExtensions string
	IsVersioning      uint8 // 1 - Yes, 0 - No
	Description       *string
	Enabled           uint8 // 1 - On, 0 - Off
	UserAdd           *uint32
	UserEdit          *uint32
	DateAdd           time.Time
	DateEdit          *time.Time
}
