//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Documents struct {
	ID             uint32 `sql:"primary_key"`
	DocumentTypeID uint32
	AccountID      uint32
	Alias          string
	Name           string
	FileName       string
	Version        int32
	FileType       *string
	UserAdd        *uint32
	DateAdd        time.Time
}
