//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type Roles struct {
	ID                       uint32 `sql:"primary_key"`
	SubserviceID             uint32
	Name                     string
	Type                     uint8 // 1 - Администратор Backend, 2- Администратор Frontend, 3 - Пользователь
	Description              *string
	TypeCategoriesRoleRights uint8
}
