//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type TendersLots struct {
	ID         uint32 `sql:"primary_key"`
	TenderID   *uint32
	CategoryID *uint32
	UnitID     *uint32
	Name       string
	Count      float64
	SortOrder  uint32
	StartPrice *float64
	Step       *float64
	IsTemplate uint8 // 0 - не шаблон, 1 - шаблон
	Formula    *string
}
