//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type TendersTypeBid string

const (
	TendersTypeBid_Tender           TendersTypeBid = "tender"
	TendersTypeBid_CollectionOffers TendersTypeBid = "collection_offers"
)

func (e *TendersTypeBid) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "tender":
		*e = TendersTypeBid_Tender
	case "collection_offers":
		*e = TendersTypeBid_CollectionOffers
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for TendersTypeBid enum")
	}

	return nil
}

func (e TendersTypeBid) String() string {
	return string(e)
}
