//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type TendersRequests struct {
	ID            uint32 `sql:"primary_key"`
	TenderID      uint32
	DateAdd       time.Time
	AccountID     uint32
	Status        uint8 // 1 - новая, 2 - принята, 3 - отклонена
	InternalCause *string
	ExternalCause *string
	Comment       *string
	UserEdit      *uint32
	DateEdit      *time.Time
}
