//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var FormulasParameters = newFormulasParametersTable("newtendex", "formulas_parameters", "")

type formulasParametersTable struct {
	mysql.Table

	// Columns
	ID           mysql.ColumnInteger
	SubserviceID mysql.ColumnInteger
	CategoryID   mysql.ColumnInteger
	Name         mysql.ColumnString
	Latter       mysql.ColumnString
	Description  mysql.ColumnString
	IsSystem     mysql.ColumnInteger
	UserAdd      mysql.ColumnInteger
	UserEdit     mysql.ColumnInteger
	DateAdd      mysql.ColumnTimestamp
	DateEdit     mysql.ColumnTimestamp

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
}

type FormulasParametersTable struct {
	formulasParametersTable

	NEW formulasParametersTable
}

// AS creates new FormulasParametersTable with assigned alias
func (a FormulasParametersTable) AS(alias string) *FormulasParametersTable {
	return newFormulasParametersTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new FormulasParametersTable with assigned schema name
func (a FormulasParametersTable) FromSchema(schemaName string) *FormulasParametersTable {
	return newFormulasParametersTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new FormulasParametersTable with assigned table prefix
func (a FormulasParametersTable) WithPrefix(prefix string) *FormulasParametersTable {
	return newFormulasParametersTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new FormulasParametersTable with assigned table suffix
func (a FormulasParametersTable) WithSuffix(suffix string) *FormulasParametersTable {
	return newFormulasParametersTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newFormulasParametersTable(schemaName, tableName, alias string) *FormulasParametersTable {
	return &FormulasParametersTable{
		formulasParametersTable: newFormulasParametersTableImpl(schemaName, tableName, alias),
		NEW:                     newFormulasParametersTableImpl("", "new", ""),
	}
}

func newFormulasParametersTableImpl(schemaName, tableName, alias string) formulasParametersTable {
	var (
		IDColumn           = mysql.IntegerColumn("id")
		SubserviceIDColumn = mysql.IntegerColumn("subservice_id")
		CategoryIDColumn   = mysql.IntegerColumn("category_id")
		NameColumn         = mysql.StringColumn("name")
		LatterColumn       = mysql.StringColumn("latter")
		DescriptionColumn  = mysql.StringColumn("description")
		IsSystemColumn     = mysql.IntegerColumn("is_system")
		UserAddColumn      = mysql.IntegerColumn("user_add")
		UserEditColumn     = mysql.IntegerColumn("user_edit")
		DateAddColumn      = mysql.TimestampColumn("date_add")
		DateEditColumn     = mysql.TimestampColumn("date_edit")
		allColumns         = mysql.ColumnList{IDColumn, SubserviceIDColumn, CategoryIDColumn, NameColumn, LatterColumn, DescriptionColumn, IsSystemColumn, UserAddColumn, UserEditColumn, DateAddColumn, DateEditColumn}
		mutableColumns     = mysql.ColumnList{SubserviceIDColumn, CategoryIDColumn, NameColumn, LatterColumn, DescriptionColumn, IsSystemColumn, UserAddColumn, UserEditColumn, DateAddColumn, DateEditColumn}
	)

	return formulasParametersTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:           IDColumn,
		SubserviceID: SubserviceIDColumn,
		CategoryID:   CategoryIDColumn,
		Name:         NameColumn,
		Latter:       LatterColumn,
		Description:  DescriptionColumn,
		IsSystem:     IsSystemColumn,
		UserAdd:      UserAddColumn,
		UserEdit:     UserEditColumn,
		DateAdd:      DateAddColumn,
		DateEdit:     DateEditColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
