//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var GroupsRecipients = newGroupsRecipientsTable("newtendex", "groups_recipients", "")

type groupsRecipientsTable struct {
	mysql.Table

	// Columns
	ID           mysql.ColumnInteger
	SubserviceID mysql.ColumnInteger
	CategoryID   mysql.ColumnInteger
	Type         mysql.ColumnBool // 1 - Список имейлов, 2 - Категория
	Name         mysql.ColumnString
	UserAdd      mysql.ColumnInteger
	UserEdit     mysql.ColumnInteger
	DateAdd      mysql.ColumnTimestamp
	DateEdit     mysql.ColumnTimestamp

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
}

type GroupsRecipientsTable struct {
	groupsRecipientsTable

	NEW groupsRecipientsTable
}

// AS creates new GroupsRecipientsTable with assigned alias
func (a GroupsRecipientsTable) AS(alias string) *GroupsRecipientsTable {
	return newGroupsRecipientsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new GroupsRecipientsTable with assigned schema name
func (a GroupsRecipientsTable) FromSchema(schemaName string) *GroupsRecipientsTable {
	return newGroupsRecipientsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new GroupsRecipientsTable with assigned table prefix
func (a GroupsRecipientsTable) WithPrefix(prefix string) *GroupsRecipientsTable {
	return newGroupsRecipientsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new GroupsRecipientsTable with assigned table suffix
func (a GroupsRecipientsTable) WithSuffix(suffix string) *GroupsRecipientsTable {
	return newGroupsRecipientsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newGroupsRecipientsTable(schemaName, tableName, alias string) *GroupsRecipientsTable {
	return &GroupsRecipientsTable{
		groupsRecipientsTable: newGroupsRecipientsTableImpl(schemaName, tableName, alias),
		NEW:                   newGroupsRecipientsTableImpl("", "new", ""),
	}
}

func newGroupsRecipientsTableImpl(schemaName, tableName, alias string) groupsRecipientsTable {
	var (
		IDColumn           = mysql.IntegerColumn("id")
		SubserviceIDColumn = mysql.IntegerColumn("subservice_id")
		CategoryIDColumn   = mysql.IntegerColumn("category_id")
		TypeColumn         = mysql.BoolColumn("type")
		NameColumn         = mysql.StringColumn("name")
		UserAddColumn      = mysql.IntegerColumn("user_add")
		UserEditColumn     = mysql.IntegerColumn("user_edit")
		DateAddColumn      = mysql.TimestampColumn("date_add")
		DateEditColumn     = mysql.TimestampColumn("date_edit")
		allColumns         = mysql.ColumnList{IDColumn, SubserviceIDColumn, CategoryIDColumn, TypeColumn, NameColumn, UserAddColumn, UserEditColumn, DateAddColumn, DateEditColumn}
		mutableColumns     = mysql.ColumnList{SubserviceIDColumn, CategoryIDColumn, TypeColumn, NameColumn, UserAddColumn, UserEditColumn, DateAddColumn, DateEditColumn}
	)

	return groupsRecipientsTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:           IDColumn,
		SubserviceID: SubserviceIDColumn,
		CategoryID:   CategoryIDColumn,
		Type:         TypeColumn,
		Name:         NameColumn,
		UserAdd:      UserAddColumn,
		UserEdit:     UserEditColumn,
		DateAdd:      DateAddColumn,
		DateEdit:     DateEditColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
