//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var Migrations = newMigrationsTable("newtendex", "migrations", "")

type migrationsTable struct {
	mysql.Table

	// Columns
	Version mysql.ColumnInteger

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
}

type MigrationsTable struct {
	migrationsTable

	NEW migrationsTable
}

// AS creates new MigrationsTable with assigned alias
func (a MigrationsTable) AS(alias string) *MigrationsTable {
	return newMigrationsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new MigrationsTable with assigned schema name
func (a MigrationsTable) FromSchema(schemaName string) *MigrationsTable {
	return newMigrationsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new MigrationsTable with assigned table prefix
func (a MigrationsTable) WithPrefix(prefix string) *MigrationsTable {
	return newMigrationsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new MigrationsTable with assigned table suffix
func (a MigrationsTable) WithSuffix(suffix string) *MigrationsTable {
	return newMigrationsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newMigrationsTable(schemaName, tableName, alias string) *MigrationsTable {
	return &MigrationsTable{
		migrationsTable: newMigrationsTableImpl(schemaName, tableName, alias),
		NEW:             newMigrationsTableImpl("", "new", ""),
	}
}

func newMigrationsTableImpl(schemaName, tableName, alias string) migrationsTable {
	var (
		VersionColumn  = mysql.IntegerColumn("version")
		allColumns     = mysql.ColumnList{VersionColumn}
		mutableColumns = mysql.ColumnList{VersionColumn}
	)

	return migrationsTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		Version: VersionColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
