//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var Roles = newRolesTable("newtendex", "roles", "")

type rolesTable struct {
	mysql.Table

	// Columns
	ID                       mysql.ColumnInteger
	SubserviceID             mysql.ColumnInteger
	Name                     mysql.ColumnString
	Type                     mysql.ColumnInteger // 1 - Администратор Backend, 2- Администратор Frontend, 3 - Пользователь
	Description              mysql.ColumnString
	TypeCategoriesRoleRights mysql.ColumnInteger

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
}

type RolesTable struct {
	rolesTable

	NEW rolesTable
}

// AS creates new RolesTable with assigned alias
func (a RolesTable) AS(alias string) *RolesTable {
	return newRolesTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new RolesTable with assigned schema name
func (a RolesTable) FromSchema(schemaName string) *RolesTable {
	return newRolesTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new RolesTable with assigned table prefix
func (a RolesTable) WithPrefix(prefix string) *RolesTable {
	return newRolesTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new RolesTable with assigned table suffix
func (a RolesTable) WithSuffix(suffix string) *RolesTable {
	return newRolesTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newRolesTable(schemaName, tableName, alias string) *RolesTable {
	return &RolesTable{
		rolesTable: newRolesTableImpl(schemaName, tableName, alias),
		NEW:        newRolesTableImpl("", "new", ""),
	}
}

func newRolesTableImpl(schemaName, tableName, alias string) rolesTable {
	var (
		IDColumn                       = mysql.IntegerColumn("id")
		SubserviceIDColumn             = mysql.IntegerColumn("subservice_id")
		NameColumn                     = mysql.StringColumn("name")
		TypeColumn                     = mysql.IntegerColumn("type")
		DescriptionColumn              = mysql.StringColumn("description")
		TypeCategoriesRoleRightsColumn = mysql.IntegerColumn("type_categories_role_rights")
		allColumns                     = mysql.ColumnList{IDColumn, SubserviceIDColumn, NameColumn, TypeColumn, DescriptionColumn, TypeCategoriesRoleRightsColumn}
		mutableColumns                 = mysql.ColumnList{SubserviceIDColumn, NameColumn, TypeColumn, DescriptionColumn, TypeCategoriesRoleRightsColumn}
	)

	return rolesTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:                       IDColumn,
		SubserviceID:             SubserviceIDColumn,
		Name:                     NameColumn,
		Type:                     TypeColumn,
		Description:              DescriptionColumn,
		TypeCategoriesRoleRights: TypeCategoriesRoleRightsColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
