//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var SubserviceCountries = newSubserviceCountriesTable("newtendex", "subservice_countries", "")

type subserviceCountriesTable struct {
	mysql.Table

	// Columns
	SubserviceID mysql.ColumnInteger
	CountryCode  mysql.ColumnString

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
}

type SubserviceCountriesTable struct {
	subserviceCountriesTable

	NEW subserviceCountriesTable
}

// AS creates new SubserviceCountriesTable with assigned alias
func (a SubserviceCountriesTable) AS(alias string) *SubserviceCountriesTable {
	return newSubserviceCountriesTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new SubserviceCountriesTable with assigned schema name
func (a SubserviceCountriesTable) FromSchema(schemaName string) *SubserviceCountriesTable {
	return newSubserviceCountriesTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new SubserviceCountriesTable with assigned table prefix
func (a SubserviceCountriesTable) WithPrefix(prefix string) *SubserviceCountriesTable {
	return newSubserviceCountriesTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new SubserviceCountriesTable with assigned table suffix
func (a SubserviceCountriesTable) WithSuffix(suffix string) *SubserviceCountriesTable {
	return newSubserviceCountriesTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newSubserviceCountriesTable(schemaName, tableName, alias string) *SubserviceCountriesTable {
	return &SubserviceCountriesTable{
		subserviceCountriesTable: newSubserviceCountriesTableImpl(schemaName, tableName, alias),
		NEW:                      newSubserviceCountriesTableImpl("", "new", ""),
	}
}

func newSubserviceCountriesTableImpl(schemaName, tableName, alias string) subserviceCountriesTable {
	var (
		SubserviceIDColumn = mysql.IntegerColumn("subservice_id")
		CountryCodeColumn  = mysql.StringColumn("country_code")
		allColumns         = mysql.ColumnList{SubserviceIDColumn, CountryCodeColumn}
		mutableColumns     = mysql.ColumnList{SubserviceIDColumn}
	)

	return subserviceCountriesTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		SubserviceID: SubserviceIDColumn,
		CountryCode:  CountryCodeColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
